name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER_NAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build Docker image
        run: |
          IMAGE_NAME="flask"
          docker build \
            -t bryamx26/$IMAGE_NAME:latest \
            -t bryamx26/$IMAGE_NAME:${GITHUB_SHA} \
            .

      - name: Push Docker image
        run: |
          IMAGE_NAME="flask"
          docker push bryamx26/$IMAGE_NAME:latest
          docker push bryamx26/$IMAGE_NAME:${GITHUB_SHA}

      - name: Replace image tag in deployment file
        run: |
          IMAGE_NAME="flask"
          sed -i "s|bryamx26/$IMAGE_NAME:.*|bryamx26/$IMAGE_NAME:${GITHUB_SHA}|g" deployment/deploy.yml

      - name: Commit changes
        run: |
          git config --global user.name "bryamx26"
          git config --global user.email "rishingsilvabryam@github.com"
          git add deployment/deploy.yml
          if ! git diff --cached --quiet; then
            git commit -m "Update image tag to ${GITHUB_SHA} in deployment file"
            git push origin HEAD:main
          else
            echo "No changes to commit, stopping workflow."

