name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  checkout:
    runs-on: ubuntu-latest
    outputs:
      changes: ${{ steps.check_changes.outputs.changes }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check if there are changes
        id: check_changes
        run: |
          # On vérifie si des fichiers ont été modifiés
          if git diff --quiet HEAD~1 HEAD; then
            echo "changes=false" >> $GITHUB_OUTPUT
          else
            echo "changes=true" >> $GITHUB_OUTPUT
          fi

  build_and_push:
    runs-on: ubuntu-latest
    needs: checkout
    if: needs.checkout.outputs.changes == 'true'
    steps:
      - uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER_NAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Build Docker image
        run: |
          IMAGE_NAME="flask"
          docker build \
            -t bryamx26/$IMAGE_NAME:latest \
            -t bryamx26/$IMAGE_NAME:${GITHUB_SHA} .
      - name: Push Docker image
        run: |
          IMAGE_NAME="flask"
          docker push bryamx26/$IMAGE_NAME:latest
          docker push bryamx26/$IMAGE_NAME:${GITHUB_SHA}

  update_deployment:
    runs-on: ubuntu-latest
    needs: build_and_push
    if: needs.build_and_push.result == 'success'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Replace image tag in deployment file
        run: |
          IMAGE_NAME="flask"
          FILE="deployment/deploy.yml"
          NEW_TAG="${GITHUB_SHA}"
          # On ne modifie le fichier que si le tag est différent
          if grep -q "bryamx26/$IMAGE_NAME:latest" "$FILE"; then
            sed -i "s|bryamx26/$IMAGE_NAME:latest|bryamx26/$IMAGE_NAME:$NEW_TAG|g" "$FILE"
            echo "Image tag updated."
          else
            echo "No update needed in $FILE."
          fi

      - name: Commit changes if there are modifications
        run: |
          git config --global user.name "bryamx26"
          git config --global user.email "rishingsilvabryam@github.com"
          git add deployment/deploy.yml
          if ! git diff --cached --quiet; then
            git commit -m "Update image tag to ${GITHUB_SHA} in deployment file"
            git push origin HEAD:main
          else
            echo "No changes to commit, stopping workflow."
          fi
